// Package content holds versioned, read-only definitions used to generate a
// world: name pools, roster template and baseline attribute ranges.
//
// Definitions are inputs, never runtime state. Changing Default's output
// changes generated worlds and requires bumping Version.
package content

import (
	"errors"
	"fmt"
	"slices"

	"github.com/thewalpa/project-zimble/internal/core/money"
	"github.com/thewalpa/project-zimble/internal/players"
)

// Version identifies the content returned by Default. Version 2 moved
// attribute ranges to the 1..100 scale; version 3 added the economy;
// version 4 added player ages and youth intake; version 5 added a second
// nation; version 6 added a second division to each nation.
const Version = 6

// Town is a fictional club home town with a unique three-letter code.
type Town struct {
	Name  string
	Short string
}

// Division is one tier of a nation's clubs, generated from its own towns.
type Division struct {
	Clubs int
	Towns []Town // at least Clubs
}

// Nation is a country whose clubs are generated from its own towns, one
// division at a time, top division first. Clubs are generated by division
// tier, then nation: every nation's top division in nation order, then every
// nation's second division, and so on. Each league takes the next block of
// clubs (see League), so with leagues in that order league i holds the
// i'th block's clubs when their sizes match. Every nation defines the same
// number of divisions.
type Nation struct {
	Name      string
	Divisions []Division // top first, at least one
}

// Quota is how many players of a position a senior squad holds. Count is
// what a generated squad contains and what AI clubs keep; Min is the fewest
// any squad may hold (1..Count). A squad may hold more than Count up to the
// total SquadLimit. The minimums must allow a legal lineup, which the
// application checks against the match rules.
type Quota struct {
	Position players.Position
	Count    int
	Min      int
}

// Range is an inclusive rating range.
type Range struct {
	Min, Max players.Rating
}

// PositionProfile gives the baseline attribute ranges for a position.
type PositionProfile struct {
	Position players.Position
	Ranges   [players.NumAttributes]Range
}

// Economy holds the money rules for generated clubs and contracts.
//
// A player's weekly wage is WageReference * (overall / ReferenceOverall)^2,
// varied uniformly by up to WageVariationPct percent and rounded to the
// nearest 10 units (never below 10). Contracts run for ContractYears[0] to
// ContractYears[1] whole contract years.
//
// A player's demand is the wage without variation. A contract offer must pay
// at least the demand and at most OfferCeilingPct percent of it.
type Economy struct {
	OpeningBalance   money.Money
	GatePerHomeMatch money.Money // paid to the home club for each league match
	WageReference    money.Money
	ReferenceOverall int
	WageVariationPct int
	ContractYears    [2]int
	OfferCeilingPct  int
}

// Wage returns the weekly wage for an overall rating and a variation in
// percent (-WageVariationPct..WageVariationPct). Integer arithmetic only;
// the result fits comfortably in an int64 for validated economies.
func (e Economy) Wage(overall, variationPct int) money.Money {
	r := int64(e.ReferenceOverall)
	w := int64(e.WageReference) * int64(overall) * int64(overall) / (r * r)
	w = w * int64(100+variationPct) / 100
	const step = 10 * money.MinorPerUnit
	w = (w + step/2) / step * step
	return money.Money(max(w, step))
}

// Demand is the weekly wage a player of this overall asks for.
func (e Economy) Demand(overall int) money.Money { return e.Wage(overall, 0) }

// OfferCeiling is the most a club may offer a player of this overall.
func (e Economy) OfferCeiling(overall int) money.Money {
	return e.Demand(overall) * money.Money(e.OfferCeilingPct) / 100
}

func (e Economy) validate() error {
	if e.OpeningBalance < 0 || e.GatePerHomeMatch < 0 || e.WageReference <= 0 || e.WageReference > money.Units(1_000_000) ||
		e.ReferenceOverall <= 0 || e.WageVariationPct < 0 || e.WageVariationPct > 90 ||
		e.ContractYears[0] < 1 || e.ContractYears[0] > e.ContractYears[1] || e.ContractYears[1] > 10 ||
		e.OfferCeilingPct < 100 || e.OfferCeilingPct > 1000 {
		return fmt.Errorf("content: invalid economy %+v", e)
	}
	return nil
}

// Youth defines the players who join clubs from their youth ranks: their
// age in whole years on joining (Ages[0]..Ages[1]), their attribute ranges
// (each position's ranges lowered by RatingGap points, never below 1) and
// the length of their first contract in contract years.
type Youth struct {
	Ages          [2]int
	RatingGap     int
	ContractYears int
}

// Range returns a youth attribute range for a position's range.
func (y Youth) Range(r Range) Range {
	lower := func(v players.Rating) players.Rating {
		return players.Rating(max(int(v)-y.RatingGap, int(players.MinRating)))
	}
	return Range{Min: lower(r.Min), Max: lower(r.Max)}
}

// Transfers defines the transfer window and how long a club has to answer
// a bid. The window opens at each contract-year end and lasts WindowDays
// days (a half-open interval: at its close no transfer may complete).
// Clubs answer bids at the first transfer run (00:00 each day of the window
// after the opening) after the bid; a manager has ResponseDays days, never
// beyond the close. WindowDays is at least 2 so that a bid made at the
// opening is answered inside the window, and well under a year so that the
// window ends before the next yearly player step.
type Transfers struct {
	WindowDays   int
	ResponseDays int
}

func (t Transfers) validate() error {
	if t.WindowDays < 2 || t.WindowDays > 180 || t.ResponseDays < 1 || t.ResponseDays > t.WindowDays {
		return fmt.Errorf("content: invalid transfers %+v", t)
	}
	return nil
}

type Definitions struct {
	Version      int
	Nations      []Nation // in generation order
	ClubSuffixes []string
	FirstNames   []string
	LastNames    []string
	Roster       []Quota // in generation order
	// SquadLimit is the most players a senior squad may hold in total; at
	// least SquadSize.
	SquadLimit int
	Profiles   []PositionProfile
	Economy    Economy
	// Ages bounds generated players' ages at the career start, in whole
	// years.
	Ages      [2]int
	Youth     Youth
	Transfers Transfers
}

// ClubCount is the number of clubs the nations generate.
func (d Definitions) ClubCount() int {
	n := 0
	for _, na := range d.Nations {
		for _, dv := range na.Divisions {
			n += dv.Clubs
		}
	}
	return n
}

// Clone returns a deep copy that shares no slices with d.
func (d Definitions) Clone() Definitions {
	d.Nations = slices.Clone(d.Nations)
	for i := range d.Nations {
		d.Nations[i].Divisions = slices.Clone(d.Nations[i].Divisions)
		for j := range d.Nations[i].Divisions {
			d.Nations[i].Divisions[j].Towns = slices.Clone(d.Nations[i].Divisions[j].Towns)
		}
	}
	d.ClubSuffixes = slices.Clone(d.ClubSuffixes)
	d.FirstNames = slices.Clone(d.FirstNames)
	d.LastNames = slices.Clone(d.LastNames)
	d.Roster = slices.Clone(d.Roster)
	d.Profiles = slices.Clone(d.Profiles)
	return d
}

// SquadSize is the number of players in each generated senior squad.
func (d Definitions) SquadSize() int {
	n := 0
	for _, q := range d.Roster {
		n += q.Count
	}
	return n
}

// Quota returns a position's roster quota; the zero Quota (no player
// allowed) for a position without one.
func (d Definitions) Quota(p players.Position) Quota {
	for _, q := range d.Roster {
		if q.Position == p {
			return q
		}
	}
	return Quota{Position: p}
}

// Profile returns the baseline profile for a position.
func (d Definitions) Profile(p players.Position) (PositionProfile, bool) {
	for _, pp := range d.Profiles {
		if pp.Position == p {
			return pp, true
		}
	}
	return PositionProfile{}, false
}

// Validate checks that the definitions can generate a valid world.
func (d Definitions) Validate() error {
	var errs []error
	if len(d.Nations) == 0 {
		errs = append(errs, errors.New("content: no nations"))
	}
	// Town names and codes are unique across nations and divisions, so club
	// names are.
	names, shorts, nations := map[string]bool{}, map[string]bool{}, map[string]bool{}
	for _, na := range d.Nations {
		if na.Name == "" || nations[na.Name] || len(na.Divisions) == 0 || len(na.Divisions) != len(d.Nations[0].Divisions) {
			errs = append(errs, fmt.Errorf("content: nation %q (%d divisions) is invalid, duplicated or has a different number of divisions", na.Name, len(na.Divisions)))
		}
		nations[na.Name] = true
		for _, dv := range na.Divisions {
			if dv.Clubs <= 0 || len(dv.Towns) < dv.Clubs {
				errs = append(errs, fmt.Errorf("content: nation %q division (%d clubs, %d towns) is invalid", na.Name, dv.Clubs, len(dv.Towns)))
			}
			for _, t := range dv.Towns {
				if t.Name == "" || t.Short == "" || names[t.Name] || shorts[t.Short] {
					errs = append(errs, fmt.Errorf("content: town %+v is empty or duplicated", t))
				}
				names[t.Name], shorts[t.Short] = true, true
			}
		}
	}
	if len(d.ClubSuffixes) == 0 || len(d.FirstNames) == 0 || len(d.LastNames) == 0 {
		errs = append(errs, errors.New("content: name pools must not be empty"))
	}
	seen := map[players.Position]bool{}
	for _, q := range d.Roster {
		if !q.Position.Valid() || q.Count <= 0 || q.Min < 1 || q.Min > q.Count || seen[q.Position] {
			errs = append(errs, fmt.Errorf("content: invalid roster quota %+v", q))
		}
		seen[q.Position] = true
		if _, ok := d.Profile(q.Position); !ok {
			errs = append(errs, fmt.Errorf("content: no attribute profile for %s", q.Position))
		}
	}
	if d.SquadSize() == 0 {
		errs = append(errs, errors.New("content: roster template is empty"))
	}
	if d.SquadLimit < d.SquadSize() {
		errs = append(errs, fmt.Errorf("content: squad limit %d below the generated squad size %d", d.SquadLimit, d.SquadSize()))
	}
	if err := d.Economy.validate(); err != nil {
		errs = append(errs, err)
	}
	if err := d.Transfers.validate(); err != nil {
		errs = append(errs, err)
	}
	// Active players are younger than players.RetirementAge.
	if d.Ages[0] < 15 || d.Ages[0] > d.Ages[1] || d.Ages[1] >= players.RetirementAge {
		errs = append(errs, fmt.Errorf("content: invalid generated ages %v", d.Ages))
	}
	if y := d.Youth; y.Ages[0] < 15 || y.Ages[0] > y.Ages[1] || y.Ages[1] >= players.FreeAgentRetirementAge ||
		y.RatingGap < 0 || y.RatingGap >= int(players.MaxRating) ||
		y.ContractYears < d.Economy.ContractYears[0] || y.ContractYears > d.Economy.ContractYears[1] {
		errs = append(errs, fmt.Errorf("content: invalid youth %+v", y))
	}
	for _, pp := range d.Profiles {
		for a, r := range pp.Ranges {
			if !r.Min.Valid() || !r.Max.Valid() || r.Min > r.Max {
				errs = append(errs, fmt.Errorf("content: %s %s range %d..%d invalid",
					pp.Position, players.Attribute(a), r.Min, r.Max))
			}
		}
	}
	return errors.Join(errs...)
}

// Default returns a fresh copy of the built-in definitions.
func Default() Definitions {
	return Definitions{
		Version: Version,
		Nations: []Nation{
			{Name: "Westmark", Divisions: []Division{
				{Clubs: 8, Towns: []Town{
					{"Brackenmoor", "BRK"}, {"Eldhaven", "ELD"}, {"Marrowdale", "MRW"},
					{"Osterholm", "OST"}, {"Quillford", "QUI"}, {"Saltmere", "SAL"},
					{"Veldmouth", "VEL"}, {"Wyrmsby", "WYR"}, {"Caldershaw", "CAL"},
					{"Dunmarrow", "DUN"}, {"Greyfen", "GRY"}, {"Hollowick", "HOL"},
				}},
				{Clubs: 8, Towns: []Town{
					{"Ambleside", "AMB"}, {"Blackwater", "BLK"}, {"Cresswell", "CRE"},
					{"Dalefield", "DAL"}, {"Elmstead", "ELM"}, {"Farthing", "FAR"},
					{"Gildermere", "GIL"}, {"Harrowgate", "HRG"}, {"Ivybridge", "IVY"},
					{"Kingsmere", "KIN"}, {"Lowenby", "LOW"}, {"Mistley", "MIS"},
				}},
			}},
			{Name: "Eastmarch", Divisions: []Division{
				{Clubs: 8, Towns: []Town{
					{"Ashcombe", "ASH"}, {"Brightwater", "BRI"}, {"Coldharbour", "COL"},
					{"Drakeford", "DRA"}, {"Emberton", "EMB"}, {"Foxmere", "FOX"},
					{"Glenrock", "GLE"}, {"Havenport", "HAV"}, {"Ironbridge", "IRO"},
					{"Juniper Vale", "JUN"}, {"Kestrel Bay", "KES"}, {"Larkspur", "LAR"},
				}},
				{Clubs: 8, Towns: []Town{
					{"Northwick", "NOR"}, {"Oakhurst", "OAK"}, {"Pinecrest", "PIN"},
					{"Ravensmoor", "RAV"}, {"Stormhaven", "STO"}, {"Thistledown", "THI"},
					{"Underhill", "UND"}, {"Westerly", "WES"}, {"Yarrowby", "YAR"},
					{"Zephyr Cove", "ZEP"}, {"Bramblecote", "BRA"}, {"Copperfield", "COP"},
				}},
			}},
		},
		ClubSuffixes: []string{"United", "Rovers", "Athletic", "Albion", "Wanderers", "Town", "City", "FC"},
		FirstNames: []string{
			"Aaron", "Ben", "Callum", "Dario", "Elias", "Felix", "Gareth", "Hugo",
			"Ivan", "Jonas", "Kofi", "Luca", "Mateo", "Nils", "Oscar", "Pavel",
			"Quentin", "Rafael", "Samir", "Tomas", "Umar", "Viktor", "Wes", "Yannick",
		},
		LastNames: []string{
			"Abbott", "Brandt", "Castell", "Doyle", "Eriksen", "Farrow", "Gallo", "Hart",
			"Ibsen", "Jansen", "Kowal", "Lindqvist", "Moreau", "Novak", "Okafor", "Pereira",
			"Quinlan", "Rossi", "Sauer", "Tanaka", "Ulrich", "Varga", "Whitlock", "Zeller",
			"Adeyemi", "Bellamy", "Costa", "Duarte", "Engel", "Fonseca", "Grady", "Holm",
		},
		Roster: []Quota{
			{players.Goalkeeper, 3, 2},
			{players.Defender, 7, 5},
			{players.Midfielder, 6, 5},
			{players.Forward, 4, 3},
		},
		SquadLimit: 25,
		// Ranges (1..100) are ordered: goalkeeping, defending, passing, finishing, pace, stamina.
		Profiles: []PositionProfile{
			{players.Goalkeeper, [players.NumAttributes]Range{{48, 90}, {11, 37}, {22, 58}, {1, 17}, {11, 48}, {27, 69}}},
			{players.Defender, [players.NumAttributes]Range{{1, 11}, {43, 90}, {22, 64}, {6, 37}, {27, 74}, {37, 84}}},
			{players.Midfielder, [players.NumAttributes]Range{{1, 11}, {22, 64}, {43, 90}, {22, 64}, {32, 74}, {43, 90}}},
			{players.Forward, [players.NumAttributes]Range{{1, 11}, {6, 37}, {27, 69}, {43, 90}, {43, 90}, {32, 74}}},
		},
		Economy: Economy{
			OpeningBalance:   money.Units(2_000_000),
			GatePerHomeMatch: money.Units(250_000),
			WageReference:    money.Units(1_600), // a squad costs about 1.7 million a year
			ReferenceOverall: 60,
			WageVariationPct: 20,
			ContractYears:    [2]int{1, 4},
			OfferCeilingPct:  200,
		},
		Ages: [2]int{17, 34},
		Youth: Youth{
			Ages:          [2]int{16, 17},
			RatingGap:     13, // keeps the long-run average overall at the generated one (about 59)
			ContractYears: 3,
		},
		Transfers: Transfers{
			WindowDays:   28, // 1 to 29 July: closed well before the first kickoff
			ResponseDays: 3,
		},
	}
}
